# Generated by Django 6.0 on 2025-12-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chai_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('description', models.TextField(max_length=100)),
                ('price', models.IntegerField()),
                ('type', models.TextField(choices=[('ms', 'masala'), ('gr', 'ginger'), ('el', 'elachi'), ('hb', 'herbal'), ('ch', 'choco')], default='')),
            ],
        ),
    ]
