# Generated by Django 6.0 on 2025-12-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chai_stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=100)),
                ('distance', models.IntegerField()),
                ('type', models.TextField(choices=[('ms', 'mansarowar'), ('gn', 'Girdhari nagar'), ('sn', 'shyam nagar'), ('ch', 'chaupad'), ('bh', 'chapra')], default='')),
            ],
        ),
    ]
